[store]
[store.primary]
connection = "postgresql://graph-node-1:password@postgres-graph-node-1:5432/graph-node-1"
pool_size = 10

[deployment]
[[deployment.rule]]
store = "primary"
indexers = ["default"]

[chains]
ingestor = "default"

[chains.mainnet]
shard = "primary"
provider = [{ label = "mainnet-0", url = "$MAINNET_RPC_URL", features = ["archive"] }]
