[store]
[store.primary]
connection = "postgresql://graph-node-1:password@postgres-graph-node-1:5432/graph-node-1"
pool_size = 10

[deployment]
[[deployment.rule]]
store = "primary"
indexers = [ "default" ]

[chains]
ingestor = "default"

[chains.mainnet]
shard = "primary"
provider = [
  { label = "mainnet-0", url="https://eth-mainnet.g.alchemy.com/v2/$ALCHEMY_MAINNET_KEY", features = ["archive"] }
]
