options:
  machineType: "N1_HIGHCPU_32"
  logging: CLOUD_LOGGING_ONLY
timeout: 1800s

steps:
  # Set the project ID
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['config', 'set', 'project', 'graph-mainnet']

  # Authenticate to GKE cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'testnet'
      - '--zone=us-central1-a'
      - '--project=graph-mainnet'

  # Update the deployment to use the latest image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/graphix-cross-checker'
      - 'graphix-cross-checker=ghcr.io/${_GITHUB_REPO_OWNER}/graphix:latest'

  # Restart the deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'restart'
      - 'deployment/graphix-cross-checker'

substitutions:
  _GITHUB_REPO_OWNER: 'edgeandnode'
