[package]
name = "graphix_autogen_config_json_schema"
version = "0.1.0"
edition = "2021"

[build-dependencies]
graphix_lib = { path = "../graphix_lib" }
schemars = { workspace = true }
serde_json = { workspace = true }
