!testing

databaseUrl: postgres://graphix:password@postgres-graphix:5432/graphix
environments:
  - id: graph-node-1
    urls:
      status: http://graph-node-1:8030/graphql
  - id: graph-node-2
    urls:
      status: http://graph-node-2:8035/graphql
