version: "3"

services:
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    # https://community.grafana.com/t/new-docker-install-with-persistent-storage-permission-problem/10896/16
    user: ":"
    depends_on:
      - prometheus
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      # Plugins:
      # - https://github.com/fifemon/graphql-datasource for GraphQL data sources.
      - GF_INSTALL_PLUGINS=fifemon-graphql-datasource
    volumes:
      - ./grafana/config/:/etc/grafana/
      - ./grafana/data:/var/lib/grafana/

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    entrypoint:
      - /bin/prometheus
      - --log.level=error
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    network_mode: host
    ports:
      - "9090:9090"
    logging:
      driver: none
    volumes:
      - ./prometheus/:/etc/prometheus/

  postgres-graphix:
    image: postgres
    restart: unless-stopped
    network_mode: host
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graphix
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
    healthcheck:
      test: psql -U graphix -c '\q' || exit 1
      interval: 1s
      timeout: 1s
      retries: 1000
    volumes:
      - ./data/postgres-graphix:/var/lib/postgresql/data
